name: post-issue
description: Post GitHub Issue
inputs:
  template-id:
    default: ""
    description: ""
    required: true
  # TODO: テンプレートの Frontmatter を解釈させたい
  title:
    default: ""
    description: ""
    required: true
runs:
  using: composite
  steps:
    - uses: actions/github-script@v6
      env:
        TEMPLATE_ID: ${{ inputs.template-id }}
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          const title = 'Title is ${{ inputs.title }}';
          let body = 'Body dayo';
          console.log(process.env.TEMPLATE_ID);
          if (process.env.TEMPLATE_ID !== '') {
            body = fs.readFileSync(path.join('.github/actions/post-issue/templates', `${ process.env.TEMPLATE_ID }.md`))
            .toString();
          }
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            labels: []
          });
