name: post-issue
description: Post GitHub Issue
inputs:
  template-id:
    default: ""
    description: ""
    required: true
  title:
    default: ""
    description: ""
    required: false
runs:
  using: composite
  steps:
    # - id: bar_content
    #   uses: juliangruber/read-file-action@v1
    #   with:
    #     path: ./.github/actions/post-issue/templates/bar.md
    - uses: actions/github-script@v6
      env:
        # BAR: ${{ steps.bar_content.outputs.content }}
        TEMPLATE_ID: ${{ inputs.template-id }}
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          const usoFrontMatterParser = require('.github/actions/post-issue/uso-front-matter-parser');
          let title = '';
          let body = '';
          if (process.env.TEMPLATE_ID !== '') {
            const template = fs.readFileSync(path.join('.github/actions/post-issue/templates', `${ process.env.TEMPLATE_ID }.md`))
              .toString();
            const parsed = usoFrontMatterParser.parse(template);
            title = parsed.title;
            body = parsed.markdown;
          }
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            labels: []
          });
