on:
  schedule:
    - cron: '45 2 * * *'
  workflow_dispatch:
jobs:
  post-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - if: github.event.schedule != '45 2 * * *'
      #   uses: ./.github/actions/post-issue
      #   with:
      #     template-id: foo
      #     title: Title defined in workflow
      - uses: ./.github/actions/post-issue
        with:
          template-id: foo
          title: Title defined in workflow
