on:
  schedule:
    - cron: '45 2 * * *'
  workflow_dispatch:
jobs:
  post-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - id: frontmatter
      #   uses: ./.github/actions/parse-frontmatter
      #   with:
      #     content: Hey
      - uses: ./.github/actions/post-issue
        with:
          template-id: foo
          # title: TITLE DAYO
