on:
  # schedule:
  #   - cron: '0 * * * *'
  #   - cron: '15 * * * *'
  #   - cron: '30 * * * *'
  #   - cron: '45 * * * *'
  workflow_dispatch:
    inputs:
      template-id:
        required: true
jobs:
  post-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - if: github.event_name == 'workflow_dispatch' 
        uses: ./.github/actions/post-issue-2
        with:
          template-id: ${{ inputs.template-id }}
      - if: github.event.schedule == '0 * * * *'
        uses: ./.github/actions/post-issue-2
        with:
          template-id: foo
      - if: github.event.schedule == '30 * * * *'
        uses: ./.github/actions/post-issue-2
        with:
          template-id: bar
