on:
  schedule:
    - cron: '45 2 0 0 0'
  workflow_dispatch:
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      # - if: github.event.schedule != '45 2 0 0 0'
      #   uses: ./.github/actions/post-issue
      #   with:
      #     template-id: foo
      #     title: Title defined in workflow
      - uses: ./.github/actions/post-issue
        with:
          template-id: foo
          title: Title defined in workflow
